version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6-node
        environment:
          - DISABLE_SPRING: true
    steps:
      - checkout
      - run: bundle install --deployment --jobs=4 --retry=3
      - run: bundle exec rspec
